### ISSUE TITLE
Playgrounds can't Connect to drone

### ISSUE THREAD

**Issue by galgenjunge** [Parrot-Developers/Drone-Swift-Playgrounds#4]
Hi I have bought a Parrot Mambo Fly Minidrone. unfortunately I can't get it connected to Playgrounds.
In the debug mode of Playgrounds I get the following crash
[Text-262EE1057917-1.txt](https://github.com/Parrot-Developers/Drone-Swift-Playgrounds/files/3711586/Text-262EE1057917-1.txt)

**Comment by JeromeBouvard** [comment]
Hello, is your drone up-to-date regarding the firmware?
What's your iPad model / iOS version / Swift PLaygrounds version?
Thanks

**Comment by BenGibbons1** [comment]
Hi,
Also having the same issue in a school. Mambo drone will not connect to Swift playground 1.4.
Was having trouble with 1.3, updated and drone appears in liveview but when connected the app crashes.
Cheers

**Comment by JeromeBouvard** [comment]
Seems I can reproduce this on iPad mini only, not on iPad pro 10"5.
It also seems to be crashing with Mambo only, not with other mini drones like airborne or rolling spider.
Give me all the info you can so that I can narrow down the bug search, thanks a lot!

**Comment by BenGibbons1** [comment]
Hi Jerome,
5th gen iPad running 13.1.2
Parrot Education Swift 5.0
Book 1.4
Mambo's updated

**Comment by JeromeBouvard** [comment]
OK, I am working on it, expect a fix early next week.
I really don't understand what causes this on some ipad and not on others...

**Comment by galgenjunge** [comment]
Hello @JeromeBouvard,

I've got 15 iPads here.
All are the following model MR7F2FD/A.
Drone is up to date
Playgrounds is on version 3.1
IPad IOS 13.1.2
Parrot Education 1.4
All Ipads have the same error

**Comment by JeromeBouvard** [comment]
Ok, I think I get it : 
for some reason (and I am still investigating that...), the release only contains @2x images files, so it will crash on some screen resolution and not on others!
I will fix this and upload a new release soon. Thanks for the prompt responses!

**Comment by JeromeBouvard** [comment]
[Parrot Template.playgroundbook.zip](https://github.com/Parrot-Developers/Drone-Swift-Playgrounds/files/3718099/Parrot.Template.playgroundbook.zip)
Could you test this template and tells me if this fixes your issues? Thanks!

**Comment by galgenjunge** [comment]
Hi, Jarrom,
Yes, the template works. Good work 👍 .
Can you still apply the change to Parrot Education?

**Comment by JeromeBouvard** [comment]
Yes, in progress, I will push the update on the official feed this WE or Monday at worst!

**Comment by JeromeBouvard** [comment]
Ok, I got the book updated, could you test it on a device that failed before to see if everything is fixed before I push it live on the stream?
[Parrot Education.playgroundbook.zip](https://github.com/Parrot-Developers/Drone-Swift-Playgrounds/files/3722484/Parrot.Education.playgroundbook.zip)

**Comment by BenGibbons1** [comment]
Hi Jerome,
Just gone 9am in australia. I will test it this morning and let you know how it goes.
Regards
BG

**Comment by BenGibbons1** [comment]
HI Jerome,
We have success! Thank you for your work and time.
Regards
BG
